PRAGMA foreign_keys = OFF;
DELETE FROM campaign_videos;
DELETE FROM campaign_images;
DELETE FROM profile_pages;
DELETE FROM profile_bms;
DELETE FROM pixel_owner_bms;
DELETE FROM bm_pixels;
DELETE FROM bm_ad_accounts;
DELETE FROM videos;
DELETE FROM video_scripts;
DELETE FROM campaigns;
DELETE FROM advertorials;
DELETE FROM ad_presets;
DELETE FROM images;
DELETE FROM temp_images;
DELETE FROM pixels;
DELETE FROM pages;
DELETE FROM ad_accounts;
DELETE FROM business_managers;
DELETE FROM profiles;
DELETE FROM product_assets;
DELETE FROM products;
DELETE FROM scaling_rules;
DELETE FROM users;
PRAGMA foreign_keys = ON;
